# Generated by Django 2.2.6 on 2019-10-14 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserURL', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 14, 8, 45, 53, 526984), verbose_name='Время начала'),
        ),
    ]
