# Generated by Django 2.2.6 on 2019-10-14 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserURL', '0002_auto_20191014_0845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 14, 8, 47, 57, 177851), verbose_name='Время начала'),
        ),
    ]
