# Generated by Django 2.2.6 on 2019-10-14 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserURL', '0004_auto_20191014_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 14, 8, 53, 25, 11200), verbose_name='Время начала'),
        ),
    ]
